const userController = require("../controller/usercontroller")
const upload=require("../middleware/fileUpload")
const router = require("express").Router()
const auth = require("../middleware/auth")
const authAdmin=require("../middleware/authAdmin")
router.post("/register", userController.add)
router.get("/all", auth, userController.show)
router.get("/alladmins",authAdmin,userController.showallAdmin)
router.get("/showsingle/:id",auth ,userController.showsingle)
router.post("/login", userController.login)
router.post("/loginAdmin", userController.loginAdmin)
router.post("/logout",auth, userController.logout)
router.post("/logoutAll", auth, userController.logoutAll)
router.post("/changePass",auth, userController.changePass)
router.post("/me",auth, userController.profile)
router.delete('/all/:id', auth, userController.del)
router.patch('/all', auth, userController.editWithToken)
router.post("/profileImg", auth, upload.single('profile'), userController.profileImg)
router.post("/addnewaAdmin", authAdmin, userController.addnewaAdmin)
router.delete("/deleteAdmin/:id", authAdmin, userController.deleteAdmin)
module.exports = router 